#!/usr/bin/env ruby

require './lib/roman_numeral_generator'

def output
  number = ARGV[0].to_i
  RomanNumeralGenerator.new(number).generate
rescue *errors => e
  e.message
end

def errors
  [RomanNumeralGenerator::ValueTooHigh, RomanNumeralGenerator::NoZeroError]
end

puts output
